config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
               :path => '', 
               :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}
  
  
  root 'pages#home'
  
  resources :users, only: [:show]
  resources :formulaires do
    resources :polls 
    member do
    get 'duplicate'
    end
  end
  resources :questions
  resources :answers, only: [:destroy]
  resources :photos

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :formulaire
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  
  has_many :photos
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  #self.inheritance_column = nil
  enum typequestion: [:reponse_courte, :choix_multiple, :choix_simple]
  
 validates :nom, presence: true
  
  

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 
   before_action :set_question, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!, except: [:show]
   #before_action :require_same_user, only: [:edit, :update]

def show 
  @answers = @question.answers
  @photos = @question.photos
end


def index
  @questions = Question.all
  #@question = current_user.questions.create(question_params)       
  #@questions = curren_user.formulaire.questions
end

def new
  #@formulaire = Formulaire.new
  #@question = @formulaire.questions.build
  @question = current_user.questions.new       
     #@question.choixes.new

end
 def edit 
    @question = Question.find params[:id]
    @question.answers.new
    @photos = @question.photos

 end
 
def create
      @question = current_user.questions.new(question_params) # on crée une nvlle entrée dans la table Question en prenant en compte les variables precedents

      if @question.save    # Si le form est sauvegardée dans la BDDon notifie le user
        #redirect_to edit_formulaire_path(@formulaire), notice: "Votre q a bien été crée"
        if params[:images]
            params[:images].each do |i|
              @question.photos.create(image: i)
          end
        end
        @photos = @question.photos
        redirect_to edit_question_path(@question), notice: "Votre question a bien été créee"

      else     #Si la q n'est pas crée alors l'user est redirigée vers la page de création new

        render :new
      end
end


def show
    #@questions = @formulaire.questions
    #@questions = @formulaire.questions
    @choixes = @question.choixes

end

def destroy
    @question = Question.find params[:id]
    @question.destroy
  respond_to do |format|
    format.html { redirect_to questions_url, notice: "La question a bien été détruite" }
    format.json { head :no_content }
  end
  redirect_back fallback_location: root_path
end

def update
    set_question
        #@question = Question.find params[:id]

    if @question.update(question_params)
        #redirect_to edit_formulaire_path(@formulaire), notice: "Votre q a bien été crée"
        if params[:images]
            params[:images].each do |i|
              @question.photos.create(image: i)
          end
        end
        @photos = @question.photos
      redirect_to edit_question_path(@question), notice: "Modification enregistrée"
    else
      render :edit
    end
    
    def require_same_user 
      if current_user.id != @question.user_id
        flash[:danger] = "Vous n'avez pas les droits"
      end
    end
    
end 






    def set_question
      @question = Question.find(params[:id])
    end
    
    def question_params         
    params.require(:question).permit(:nom, :typequestion, :media, choixes_attributes: [:id, :choix]) 
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for (@question), html: {multipart: true} do |f| %>
  <!--
  <div class="field">
    <%= f.text_field :formulaire_id %>
  </div>
  -->
  <div class="row">
    <div class="form-group col-md-8">
        <label>Nom de la question :</label>
            <%= f.text_field :nom, placeholder: "Nom de la question", class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-8">
        <label>Type de question :</label>
            <%= f.select :typequestion,[["Choix multiples",1],["Choix simple",2],["Reponse courte",3]],prompt: "Sélectionner le type de qu", class: "form-control" %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-4">
      <span class="btn btn-default btn-file">
        <i class="fa fa-cloud-upload fa-lg"></i> DL vos photos 
        <%= file_field_tag "images[]", type: :file, multiple: :true %>
      </span>
    </div>
  </div>
  
  <div id="photos"><%= render 'photos/list' %></div>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Formulaire</th>
      <th>Nom</th>
      <th>Typequestion</th>
      <th>Media</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.formulaire %></td>
        <td><%= question.nom %></td>
        <td><%= question.typequestion %></td>
        <td><%= question.media %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Formulaire:</strong>
  <%= @question.formulaire %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @question.nom %>
</p>

<p>
  <strong>Typequestion:</strong>
  <%= @question.typequestion %>
</p>

<p>
  <strong>Media:</strong>
  <%= @question.media %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>