config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
               :path => '', 
               :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}
  
  
  root 'pages#home'
  
  resources :users, only: [:show]
  resources :formulaires do
    resources :polls 
    member do
    get 'duplicate'
    end
  end
  resources :questions
  resources :answers, only: [:destroy]
  resources :photos

end

app/models/formulaire.rb
class Formulaire < ActiveRecord::Base

  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :polls
  
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:nom].blank? }, :allow_destroy => true
  
  
  validates :name, presence: true

    HUMANIZED_ATTRIBUTES = {
    :name => "Le nom du formulaire",
    :description => "La description du formulaire"
  }
    def self.human_attribute_name(attr, options = {})
     HUMANIZED_ATTRIBUTES[attr.to_sym] || super
    end

end

app/controllers/formulaires_controller.rb
class FormulairesController < ApplicationController
  before_action :set_formulaire, only: [:show, :edit, :update, :destroy]  
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update]

  # GET /formulaires
  # GET /formulaires.json
def index
    if current_user
      @formulaires = current_user.formulaires.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
      

    else 
      @formulaires = Formulaire.all.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
    end
end

def show
    @questions = @formulaire.questions
end

def new
  @formulaire = Formulaire.new
  #@question = @formulaire.questions.build
  #@answer = @question.answers.build

    if false
      @question.answers.build
      2.times do
      question = @formulaire.questions.build
      2.times { question.answers.build }
      end
    end
end
  
def edit
    @formulaire = Formulaire.find(params[:id])
    #@formulaire.questions.new  #Ici on crée les champs de création de Question
end

def create
    #puts formulaire_params.inspect
    #@formulaire = Formulaire.new(formulaire_params)
    @formulaire = current_user.formulaires.new(formulaire_params)
      if @formulaire.save    # Si le form est sauvegardée dans la BDDon notifie le user
        redirect_to @formulaire, notice: "Votre formulaire a bien été crée"   #Cette config est mieux que la suivante
      else     #Si le form n'est pas crée alors l'user est redirigée vers la page de création new
        render :new
      end
end

def update
  set_formulaire
    if @formulaire.update(formulaire_params)
      redirect_to @formulaire, notice: "Modification(s) enregistrée(s)"
    else
      render :edit
    end
end

def  duplicate
  
  #===================================================== Duplique le formulaire (id nom, description) ==============================================
 formulaire = Formulaire.find(params[:id])
 #create new object with attributes of existing record 
 @formulaire2 = formulaire.dup
 @formulaire2.save
#===================================================================================================================================================
#================================================================== Duplique les questions =========================================================
 a= Question.find_by_sql(["Select * from questions where formulaire_id=?", formulaire.id]).as_json
 a_size = Question.find_by_sql(["Select * from questions where formulaire_id=?", formulaire.id]).size
     liste_question= []                                         #Liste des id des questions a récupérer pour écrire les réponses
b = []
(0..a_size-1).each do |i|

  Question.create formulaire_id: (@formulaire2.id), #On recupère le  formulaire_id contenant toutes les questions
                  nom: (a[i]["nom"]), 
                  typequestion: (a[i]["typequestion"]), 
                  media: (a[i]["media"]), 
                  user_id: (a[i]["user_id"]),
                  image_file_name: (a[i]["image_file_name"]),
                  image_content_type:(a[i]["image_content_type"]),
                  image_file_size: (a[0]["image_file_size"])
                  
#=================================================================================================================================================
                  
  liste_question.push(Question.find_by_sql(["Select * from questions where formulaire_id=?", formulaire.id]).as_json[i]["id"])
  #On veut récupérer la liste des questions id de base pour récupérer nos infos
  #Question.find_by_sql(["Select * from questions where formulaire_id=?", @formulaire2.id])[i].id)

#================================================================ Duplique les réponses ==========================================================

    b = Answer.find_by_sql(["Select * From answers where question_id=?", liste_question[i]]).as_json
    b_size = Answer.find_by_sql(["Select * From answers where question_id=?",liste_question[i]]).size

    (0..b_size-1).each do |j|              #On met ensuite nos nouveaux infos dans les bons questions id
        Answer.create formulaire_id: (@formulaire2.id),
                      question_id: (Question.find_by_sql(["Select * from questions where formulaire_id=?", @formulaire2.id]).as_json[i]["id"]),
                      content: (Answer.find_by_sql(["Select * From answers where question_id=?",liste_question[i]])[j]["content"])
    end
end
#===============================================================================================================================================
  #render :text => b.inspect   #Récupère les bons questions id à duppliquer
  if @formulaire2.save
    #render :text => liste_question[0].inspect   #Récupère les bons questions id à duppliquer
    redirect_to @formulaire2 ,notice: "Formulaire dupliqué"
  else
    render :new # This can be a render or redirect or whatever should happen if it fails
  end
  
end



def destroy
    @formulaire.destroy
    respond_to do |format|
      format.html { redirect_to formulaires_url, notice: "Le formulaire a bien été supprimé" }
      format.json { head :no_content }
    end
end


    # Use callbacks to share common setup or constraints between actions.
def set_formulaire
   @formulaire = Formulaire.find(params[:id])
   @question = @formulaire.questions

end
    
   
def formulaire_params
          params.require(:formulaire).permit(:name, :description, 
                  questions_attributes: [:id, :nom, :typequestion, :image, :maxmultiplechoice, :obligatoire, '_destroy', 
                      answers_attributes:[:id, :content,'_destroy']]) if params[:formulaire]
          
          #puts YAML::dump params
end
    
def require_same_user 
      if current_user.id != @formulaire.user_id
        flash[:danger] = "Vous n'avez pas les droits"
      end
end
    
def your polls
end
    
end

app/helpers/formulaires_helper.rb
module FormulairesHelper
end

app/views/formulaires/_answer_fields.html.erb
<div class="nested">
   <div class ="nested-fields">  
<p class ="fields">
  <%= f.text_field :content ,placeholder: "Nouveau choix"%>
  <%= f.hidden_field :_destroy %>

    <%= link_to_remove_association '', f, class: 'btn btn-warning fa fa-trash-o' %>


</p>
</div>
</div>

app/views/formulaires/_form.html.erb
<div class="panel panel-primary">
    <div class="panel-heading">
        Créer un formulaire
    </div>
    
    
    <div class="panel-body">
        <div class= "col-md-10">
            <div class="form-group">

            <%= form_for @formulaire, html: {multipart: true} do |f| %>
              <% if @formulaire.errors.any? %> 
                <div class="col-md-6">
                    <div class="panel panel-danger">
                          <div class="panel-heading">
                            <h5>Erreurs :</h5>
                          </div>
                          <div class="panel-body">
                                <ul>
                                <% @formulaire.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                <% end %>
                                </ul>
                          </div>
                        
                  </div>    
                </div>
              <% end %>
                
                  <div class="row">
                    <div class="form-group col-md-8">
                    <%= f.label :name, "Nom du formulaire" %><br />
                    <%= f.text_field :name, class: "form-control" %>
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class="form-group col-md-8">
                    <%= f.label :description, "Description du Formulaire" %><br />
                    <%= f.text_area :description, class: "form-control" %>
                    </div>
                  </div>
                    <br/><hr/><br/>
                

                <div class="col-md-11"> 
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            Questions
                        </div>
                        <div class="panel-body">
                          <%= f.fields_for :questions, html: {multipart: true} do |builder| %>

                            <%= render 'question_fields', f: builder %>
                            
                          <% end %>
                          </div>
          <div class="centerbutton">
                  <%= link_to_add_association 'Ajouter une question', f, :questions, class: "btn btn-success"   %>
          </div><br/>

  
                </div>
                  <div class="actions">
                    <%= f.submit "Valider le formulaire", class:"pull-right btn btn-primary" %>
                  </div>
                  </div>
                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/formulaires/_question_fields.html.erb
<div class="nested">
   <div class ="nested-fields">  

          <hr>
            <%= f.label :nom, "Question :" %> </br>
                <span>

                  <% f.trix_editor :nom, placeholder: "Intitulé de la question", cols: 130, rows: 2, class: "form-control" %></br>
                  <%= tinymce %> 
                  <%= f.text_area :nom, rows: 5, cols: 25, :class => "tinymce" %>

                  <%= f.label :typequestion, "Type de question"  %>
                  <%= f.select :typequestion, Question.typequestions.keys.map(&:humanize).zip(Question.typequestions
                  .keys), placeholder: "Type", class: "form-control" %>
                              <i class="fa fa-question-circle-o"  
                              title="Choix multiple : Réponse simple : Champ libre (max, 100 caractères) - Plusieurs réponses à la question - Choix simple : Une seule réponse par question ">
                              </i> 
                  <!-- Ne faire apparaitre cette div que si le select type de question vaut choix multiple
                  <div class="maxmultiplechoice">
                    < %= f.label :maxmultiplechoice, "Nombre de réponses maximum"  %>
                    < %= f.number_field :maxmultiplechoice %>
                  </div>
                  -->
                  
                  <!-- Question obligatoire non fonctionnelle
                  <div class="questionobligatoire">
                    < %= f.label :obligatoire, "Réponse obligatoire"  %>
                    < %= f.check_box :obligatoire %>
                  </div>
                  -->
              <div class="row">
                <div class="col-md-4">
                  <%= f.file_field :image, title: "Ajouter une image pour illustrer votre question" %>
              </div>
              <div class="col-md-6"></div>
                <%= link_to_remove_association '', f,class: 'btn btn-danger fa fa-trash-o', title: 'Supprimer la question' %><br/>

            </div> 

                </span></br>
            
              <%= f.fields_for :answers do |builder2| %>
              <%= render 'answer_fields', f: builder2 %>
              <% end %>
            
        </hr>
              <span>
                    <%= link_to_add_association 'Ajouter un choix', f, :answers, class: "btn btn-primary" %>
              </span> <br/> 
  </div> 
</div>
<br/> 

app/views/formulaires/edit.html.erb
<%= render 'form' %>
<div class="clearfix"></div>

<ul class="pager">
    <li class="Show"><%= link_to 'Show', @formulaire %> </li>
    <li class="Retour"><%= link_to 'Back', formulaires_path %></li>
</ul>

app/views/formulaires/index.html.erb
<div class="text-center">
    <h1> Bienvenue sur le générateur de formulaires d'Agria Grand Est  </h1>
</div>
<br/><br/>


<div class="col-md-3">
    <div class="panel panel-primary">
        <div class="panel-body" style="background-color:#D8D8D8"><center>
                        <div class="text-center-md"><%= link_to new_formulaire_path do %>Créer un formulaire
                        <br/>
                        <i class="fa fa-plus fa-5x"></i>
                        </div><% end %></center>
                        </br>
        </div>
    </div>   
</div>

<% @formulaires.each do |formulaire| %>
<div class="col-md-4">
    
    <div class="panel panel-primary">
        <div class="panel-heading">
         <%= formulaire.name %>
             <div class="text-right"> 
                Crée par <%= formulaire.user.prenom %> <%= formulaire.user.nom %> le <%= formulaire.updated_at.strftime("%d/%m/%Y")   %>
             </div>
     
     
        </div>
        
        <div class="panel-body">
            <div class= "col-md-12">
                <!--<div class="container">-->
                  <td><%= formulaire.description %></td>
                    </br>
                    <div class ="col-md-12 text-center"><hr/>
                    <table>
                    <td style="padding-left: 1px"><%= link_to '  Show ', formulaire , class: "fa fa-television"%></td>
                    <td style="padding-left: 25px"><%= link_to '  Dupliquer  ', duplicate_formulaire_path(formulaire) , class: "fa fa-clone" %></td>
                    <td style="padding-left: 25px"><%= link_to '  Editer', edit_formulaire_path(formulaire), class: "fa fa-pencil-square-o" %></td>
                    <td style="padding-left: 25px"><%= link_to '  Supprimer', formulaire, method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer ce formulaire ?' }, class: "fa fa-trash-o" %> </td>
                    </table>
                    </div>
<!--                </div>    -->
            </div>
        </div>
    </div> 
    </br></br>
</div>
<div class="col-md-3">
</div>

<% end %>
<div class="clearfix"></div>

<div class="col-md-6 col-md-offset-5">
<%= will_paginate @formulaires , :previous_label => 'Page précédente',:page_gap => '...', :next_label => 'Page suivante' %> </br></br></br></br></br></br>
</div>

app/views/formulaires/new.html.erb
<%= render 'form' %>
<div class="clearfix"></div>

<ul class="pager">
    <li class="Retour"><%= link_to 'Back', formulaires_path %></li>
</ul>

app/views/formulaires/show.html.erb
<div class="panel panel-primary">
    <div class="panel-heading">
        <%= @formulaire.name %>
    </div>
    <div class="panel-body">
        <%= @formulaire.description %>
        <br/><hr/>
        
            <ol>
                <% for question in @formulaire.questions %>
                    <br/>
                    <li> 
                        <%=h question.nom.html_safe %>
                        <div class="row" id="imageshow">
                            <% if question.image_content_type != nil %>
                                <div class = "container">
                                    <div class="col-md-2 col-md-offset-1">
                                        <%= image_tag(question.image, :size => "400x400" )%>
                                    </div>
                                </div>
                            <% end %>
                        </div>                  
                        <ul>
                            <% for answer in question.answers %>
                                <% if (question.typequestion == 'choix_simple' || question.typequestion== 'choix_multiple') %>
                                <li><%=h answer.content %></li>
                                <%end%>
                            <% end %>
                        </ul>
                        </li>
                <% end %>
                
            </ol>

    </div>
</div>


<ul class="pager">
    <li class="Retour"><%= link_to 'Retour', formulaires_path %> </li>
    <li class="Edit"><%= link_to 'Editer', edit_formulaire_path(@formulaire) %>  </li>
    <li class="Repondre"><%= link_to 'Répondre', new_formulaire_poll_path(@formulaire) %> </li>
    <li class="Dupliquer"><%= link_to 'Dupliquer', duplicate_formulaire_path(@formulaire)  %> </li> 
    <li class="Voir les réponses"><%= link_to 'Voir toutes les réponses', formulaire_polls_path(@formulaire) %> </li>

</ul>